ngr: Fix Java/Gradle on CI/GHA
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
tests/test_ngr.py::test_ngr_sample[ngr/java-gradle] FAILED

Tested on both version 11 and version 17.